before_install:
  - gem update --system
  - gem --version
language: ruby
rvm:
  - 2.2.5
  - 2.3.1
  - jruby-9.1.13.0
services:
  - mongodb
matrix:
  allow_failures:
    - rvm: ruby-head
  include:
    - rvm: 2.3.1
      env: MONGOID_VERSION=3
    - rvm: 2.3.1
      env: MONGOID_VERSION=4
    - rvm: 2.3.1
      env: MONGOID_VERSION=5
    - rvm: 2.3.1
      env: MONGOID_VERSION=6
    - rvm: 2.3.1
      env: MONGOID_VERSION=7
